apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-apps
  namespace: default
spec:
  components:
  - name: apps
    type: kustomize
    properties:
      repoType: git
      url: http://10.55.10.16:8090/zhangjy/KubeVela-GitOps-Infra-Demo.git
      secretRef: git-secret
      pullInterval: 1m
      git:
        branch: master
      path: ./apps
      imageRepository:
        image: registry.cn-beijing.aliyuncs.com/zaq1/nginx
        secretRef: imagesecret
        filterTags:
          pattern: '^dev-[a-f0-9]+-(?P<ts>[0-9]+)'
          extract: '$ts'
        policy:
          numerical:
            order: asc
        commitMessage: "Image: {{range .Updated.Images}}{{println .}}{{end}}"
  - name: apps2
    type: kustomize
    properties:
      repoType: git
      url: http://10.55.10.16:8090/zhangjy/KubeVela-GitOps-Infra-Demo.git
      secretRef: git-secret
      pullInterval: 1m
      git:
        branch: master
      path: ./apps
      imageRepository:
        image: registry.cn-beijing.aliyuncs.com/zaq1/nginx2
        secretRef: imagesecret
        filterTags:
          pattern: '^dev-[a-f0-9]+-(?P<ts>[0-9]+)'
          extract: '$ts'
        policy:
          numerical:
            order: asc
        commitMessage: "Image: {{range .Updated.Images}}{{println .}}{{end}}"