apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: infra
spec:
  components:
  - name: database-config
    type: kustomize
    properties:
      repoType: git
      url: http://10.55.10.16:8090/zhangjy/KubeVela-GitOps-Infra-Demo
      secretRef: git-secret
      pullInterval: 10m
      git:
        branch: main
      path: ./infrastructure
